### ISSUE TITLE
Please fix this - 

### ISSUE THREAD

**Issue by stephaniekerr922** [Mikek2252/wedding-site#1]
You haven’t included an option for the guests to put in their dietary requirements.. for example: allergies or gluten free/vegan or something ❤️

Please also add gift poem and option for guests to request a song! 

Thank you 😊

**Comment by stephaniekerr922** [comment]
@mikek2252

**Comment by Mikek2252** [comment]
Done the Gift Poem, need to do song bit still

**Comment by Mikek2252** [comment]
And dietary requirements

**Comment by Mikek2252** [comment]
Done dietary requirements

**Comment by stephaniekerr922** [comment]
Can’t wait to see it all 😍
