### ISSUE TITLE
Fix Nav Bar headings

### ISSUE THREAD

**Issue by Mikek2252** [Mikek2252/wedding-site#13]

**Comment by Mikek2252** [comment]
Done need to check with steph

**Comment by callustheparkers** [comment]
Has this been resolved?

**Comment by Mikek2252** [comment]
Kinda need to check the names will do it with you both next weekend

**Comment by stephaniekerr922** [comment]
What do I need to check?

**Comment by Mikek2252** [comment]
dont worry about this one for now

**Comment by stephaniekerr922** [comment]
Can we have Gift registry maybe? To sound nicer?

**Comment by stephaniekerr922** [comment]
Maybe a getting here page?

**Comment by Mikek2252** [comment]
hmm, the map stuff is part of the venue should i change 'venue' to 'getting here'

**Comment by stephaniekerr922** [comment]
No venue is fine if it’s got the information on xx
