### ISSUE TITLE
Evening  details

### ISSUE THREAD

**Issue by callustheparkers** [Mikek2252/wedding-site#19]
Notes on cards accepted at bar aswell as cash. @

**Comment by Mikek2252** [comment]
Where is the best place to put this?

**Comment by stephaniekerr922** [comment]
Umm you can leave this off for now - when we have confirmed the order of service maybe we can add it on then at the bottom? Or do you think we should say it before then?

**Comment by Mikek2252** [comment]
Okay, i wasn't sure whether you wanted a evening section
